[package]
name = "nazoauth-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
nazo-crypto = { path = "../crates/crypto", features = ["ed25519"] }
libfuzzer-sys = "0.4"
nazo-operator-protocol = { path = "../crates/operator-protocol" }

[[bin]]
name = "operator_jws_parser"
path = "fuzz_targets/operator_jws_parser.rs"
test = false
doc = false
bench = false
