ALTER TABLE users
    ADD COLUMN IF NOT EXISTS given_name VARCHAR(80),
    ADD COLUMN IF NOT EXISTS family_name VARCHAR(80),
    ADD COLUMN IF NOT EXISTS middle_name VARCHAR(80),
    ADD COLUMN IF NOT EXISTS nickname VARCHAR(80),
    ADD COLUMN IF NOT EXISTS profile_url VARCHAR(512),
    ADD COLUMN IF NOT EXISTS website_url VARCHAR(512),
    ADD COLUMN IF NOT EXISTS gender VARCHAR(40),
    ADD COLUMN IF NOT EXISTS birthdate VARCHAR(10),
    ADD COLUMN IF NOT EXISTS zoneinfo VARCHAR(64),
    ADD COLUMN IF NOT EXISTS locale VARCHAR(35);
