ARG HYDRA_IMAGE_TAG=v26.2.0

FROM docker.io/busybox:1.36.1-musl AS busybox

FROM docker.io/oryd/hydra:${HYDRA_IMAGE_TAG}

USER root
COPY --from=busybox /bin/busybox /usr/local/bin/busybox
RUN /usr/local/bin/busybox --install -s /usr/local/bin
USER 1000
