mod admin;
mod auth;
mod authorization;
mod dynamic_client_registration;
mod fapi_resource;
mod perf_metrics;
mod profile;
mod scim;
mod token;
mod well_known;

pub(crate) use admin::*;
pub(crate) use auth::*;
pub(crate) use authorization::*;
pub(crate) use dynamic_client_registration::*;
pub(crate) use fapi_resource::*;
pub(crate) use perf_metrics::*;
pub(crate) use profile::*;
pub(crate) use scim::*;
pub(crate) use token::*;
pub(crate) use well_known::*;
