from pathlib import Path
import json
E=Path('/src/evidence/model-consolidation-20261009');out=[]
for key in ['MODEL02','MODEL10','MODEL03','MODEL04']:
 fs=list((E/key).glob('**/short-result.json'))
 if not fs:continue
 r=json.loads(fs[0].read_text());m=r['metrics'];w=m['measure'];q=json.loads((E/key/'requests'/f'{key}.json').read_text());samples=[json.loads(l) for l in next((E/key).rglob('soak-metrics.jsonl')).read_text().splitlines()];samples=[s for s in samples if 'ts' in s];last=samples[-1];storage=[json.loads(l) for l in (E/key/'storage.jsonl').read_text().splitlines()]
 summary=json.loads(next(p for p in (E/key).rglob('*summary.json') if p.parent.name=='load').read_text());warmup=summary['k6']['measure']['measurement_contract']['warmup_ms']/1000
 row={'key':key,'warmup_seconds':warmup,'steps':summary.get('steps'),'source_sha':q['source_sha'],'binary_sha256':q['expected_binary_sha256'],'diagnostic_only':q.get('diagnostic_only',False),'scenario':r['scenario'],'target_ops_s':r['rate'],'app_cpus':len(q['app_cpus']),'pre_vus':q['pre_vus'],'max_vus':q['max_vus'],'pool_connections':q['pool_connections'],'app_env_overrides':q['app_env_overrides'],'formal_window_seconds':r['window_seconds'],'window':w,'verdict':r['verdict'],'successful_ops_s':m['successful_ops_s'],'complete_operation_ms':m['complete_operation_latency_ms'],'outcomes':w['measure_outcomes'],'unfinished':w['measure_started_exact']-w['measure_completed_exact'],'drop_fraction':w['measure_drop_fraction'],'success_over_planned':w['measure_outcomes'].get('success',0)/w['measure_scheduled_observed'],'wal_bytes_per_success':r['cost']['wal_per_success_bytes'],'cpu_cores':r['component_cpu_cores'],'db_sample_first_bytes':storage[0]['db_bytes'],'db_sample_last_bytes':storage[-1]['db_bytes'],'db_sample_seconds':storage[-1]['ts']-storage[0]['ts'],'valkey_last_bytes':last.get('vk',{}).get('mem'),'health':r['health'],'audit':{'verdict':r['audit']['verdict'],'delta_events':r['audit']['delta_events'],'receiver_events':r['audit']['accepted_events_delta'],'checks':r['audit']['checks']},'subject_lifecycle':m.get('subject_lifecycle'),'reported_run_seconds':r['elapsed_s']};out.append(row)
(E/'acceptance-metrics.json').write_text(json.dumps(out,indent=2));print([(r['key'],r['verdict'],r['successful_ops_s'],r['complete_operation_ms'],r['drop_fraction']) for r in out])

