FROM docker.io/library/python:3.14-alpine@sha256:c6ead215bfd31f1e433d968853b7a769989117115b728874824e6c0a27cb96fc

RUN apk add --no-cache openssl

COPY scripts/ensure_runtime_keyset.py /scripts/ensure_runtime_keyset.py

CMD ["python", "/scripts/ensure_runtime_keyset.py"]
